name: Chat app Node-Js

on:
  push:
    branches:
      - main
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Linking project to Vercel
      run: npx vercel link --yes --project ladidas-bakery --token=${{ secrets.VERCEL_TOKEN }}

    - name: Run Database Migrations
      run: npx sequelize-cli db:migrate --env production
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_DIALECT: 'mysql'



    - name: Deploy to vercel
      run: npx vercel --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
      




